CREATE TABLE `ficha_bancos` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fichaId` int NOT NULL,
	`banco` varchar(100) NOT NULL,
	`status_banco` enum('pendente','em_analise','aprovado','recusado') NOT NULL DEFAULT 'pendente',
	`observacao` text,
	`valorParcela` int,
	`qtdParcelas` int,
	`taxaJuros` varchar(20),
	`tentadoPorVendedor` boolean DEFAULT false,
	`atualizadoPor` varchar(255),
	`atualizadoEm` bigint,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ficha_bancos_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `fichas_financiamento` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sellerId` int NOT NULL,
	`competitionId` int,
	`status` enum('na_fila','em_analise','aprovado','recusado','parcial') NOT NULL DEFAULT 'na_fila',
	`veiculo` varchar(255),
	`placa` varchar(10),
	`anoModelo` varchar(20),
	`valorFipe` int,
	`valorFinanciado` int,
	`nomeCompleto` varchar(255) NOT NULL,
	`cpf` varchar(20) NOT NULL,
	`rg` varchar(30),
	`dataNascimento` varchar(20),
	`estadoCivil` varchar(50),
	`nomeMae` varchar(255),
	`nomePai` varchar(255),
	`cidadeNasceu` varchar(255),
	`email_ficha` varchar(320),
	`telefone` varchar(30),
	`cep` varchar(15),
	`endereco` text,
	`profissao` varchar(255),
	`renda` varchar(100),
	`localTrabalho` varchar(255),
	`referenciaNome` varchar(255),
	`referenciaTelefone` varchar(30),
	`cnhFotoUrl` text,
	`cnhFotoKey` varchar(500),
	`observacoesVendedor` text,
	`observacoesFei` text,
	`feiResponsavelId` int,
	`feiResponsavelNome` varchar(255),
	`inicioAnalise` bigint,
	`fimAnalise` bigint,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `fichas_financiamento_id` PRIMARY KEY(`id`)
);
