CREATE TABLE `super_admins` (
	`id` int AUTO_INCREMENT NOT NULL,
	`username` varchar(100) NOT NULL,
	`passwordHash` varchar(255) NOT NULL,
	`name` varchar(255) NOT NULL,
	`email` varchar(320),
	`super_role` enum('owner','support') NOT NULL DEFAULT 'support',
	`active` boolean NOT NULL DEFAULT true,
	`lastAccess` bigint,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `super_admins_id` PRIMARY KEY(`id`),
	CONSTRAINT `super_admins_username_unique` UNIQUE(`username`)
);
--> statement-breakpoint
CREATE TABLE `tenants` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`slug` varchar(100) NOT NULL,
	`logoUrl` text,
	`logoKey` varchar(500),
	`phone` varchar(20),
	`email` varchar(320),
	`address` text,
	`city` varchar(100),
	`state` varchar(2),
	`primaryColor` varchar(20) DEFAULT '#DC2626',
	`secondaryColor` varchar(20) DEFAULT '#1F2937',
	`plan` enum('trial','basic','pro','enterprise') NOT NULL DEFAULT 'trial',
	`maxSellers` int NOT NULL DEFAULT 10,
	`maxAdmins` int NOT NULL DEFAULT 2,
	`enabledModules` text,
	`zapiInstanceId` varchar(255),
	`zapiToken` varchar(500),
	`zapiClientToken` varchar(500),
	`inventoryUrl` text,
	`tenant_status` enum('active','suspended','cancelled','trial') NOT NULL DEFAULT 'trial',
	`trialEndsAt` bigint,
	`subscriptionId` varchar(255),
	`monthlyPrice` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `tenants_id` PRIMARY KEY(`id`),
	CONSTRAINT `tenants_slug_unique` UNIQUE(`slug`)
);
