CREATE INDEX `idx_action_plans_tenant` ON `action_plans` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_ai_conversation_logs_tenant` ON `ai_conversation_logs` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_app_settings_tenant` ON `app_settings` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_bonus_vehicles_tenant` ON `bonus_vehicles` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_bracket_matches_tenant` ON `bracket_matches` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_commission_rules_tenant` ON `commission_rules` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_competition_participants_tenant` ON `competition_participants` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_competition_snapshots_tenant` ON `competition_snapshots` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_competitions_tenant` ON `competitions` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_consignment_records_tenant` ON `consignment_records` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_crm_activities_tenant` ON `crm_activities` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_crm_bulk_send_logs_tenant` ON `crm_bulk_send_logs` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_crm_campaigns_tenant` ON `crm_campaigns` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_crm_follow_up_tasks_tenant` ON `crm_follow_up_tasks` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_crm_integrations_tenant` ON `crm_integrations` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_crm_inventory_tenant` ON `crm_inventory` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_crm_inventory_alerts_tenant` ON `crm_inventory_alerts` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_crm_lead_distribution_tenant` ON `crm_lead_distribution` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_crm_leads_tenant` ON `crm_leads` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_crm_message_templates_tenant` ON `crm_message_templates` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_crm_messages_tenant` ON `crm_messages` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_crm_pipeline_stages_tenant` ON `crm_pipeline_stages` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_dispatch_records_tenant` ON `dispatch_records` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_fei_audit_logs_tenant` ON `fei_audit_logs` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_fei_records_tenant` ON `fei_records` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_feirao_editions_tenant` ON `feirao_editions` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_ficha_bancos_tenant` ON `ficha_bancos` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_fichas_financiamento_tenant` ON `fichas_financiamento` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_fin_categories_tenant` ON `fin_categories` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_fin_transactions_tenant` ON `fin_transactions` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_fuel_records_tenant` ON `fuel_records` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_goals_tenant` ON `goals` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_iam_config_tenant` ON `iam_config` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_inventory_sync_logs_tenant` ON `inventory_sync_logs` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_inventory_vehicles_tenant` ON `inventory_vehicles` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_manager_alerts_tenant` ON `manager_alerts` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_manager_mentor_messages_tenant` ON `manager_mentor_messages` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_manager_permissions_tenant` ON `manager_permissions` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_manager_tasks_tenant` ON `manager_tasks` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_mkt_strategies_tenant` ON `mkt_strategies` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_mkt_tasks_tenant` ON `mkt_tasks` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_monthly_snapshots_tenant` ON `monthly_snapshots` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_motivational_quotes_tenant` ON `motivational_quotes` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_notifications_tenant` ON `notifications` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_push_subscriptions_tenant` ON `push_subscriptions` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_pv_chamados_tenant` ON `pv_chamados` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_pv_gastos_tenant` ON `pv_gastos` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_pv_historico_tenant` ON `pv_historico` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_pv_oficinas_tenant` ON `pv_oficinas` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_pv_orcamento_itens_tenant` ON `pv_orcamento_itens` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_pv_orcamentos_tenant` ON `pv_orcamentos` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_sale_documents_tenant` ON `sale_documents` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_sales_tenant` ON `sales` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_sdr_records_tenant` ON `sdr_records` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_seller_advances_tenant` ON `seller_advances` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_seller_bonuses_tenant` ON `seller_bonuses` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_seller_permissions_tenant` ON `seller_permissions` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_teams_tenant` ON `teams` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_trainings_tenant` ON `trainings` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_users_tenant` ON `users` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_vehicle_cost_items_tenant` ON `vehicle_cost_items` (`tenantId`);--> statement-breakpoint
CREATE INDEX `idx_vehicle_costs_tenant` ON `vehicle_costs` (`tenantId`);